name: Run PR workflow
on:
  pull_request

jobs: 
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Build Code
        run: npm run build